# Generated by Django 4.0.6 on 2022-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_posting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='file',
            field=models.ImageField(upload_to='uploads/imageboard'),
        ),
    ]
